name: cenroapp
description: Offline Certificate of Inspection generator for City Government of Puerto Princesa.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  pdf: ^3.10.6
  printing: ^5.11.1
  excel: ^4.0.2
  permission_handler: ^11.0.1
  intl: ^0.18.1
  external_path: ^2.2.0
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
