# Generated by Django 5.2.7 on 2026-03-16 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=50, unique=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_address', models.TextField()),
                ('license_type', models.CharField(max_length=20)),
                ('nature_of_business', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('contact_number', models.CharField(max_length=50)),
                ('issued_date', models.CharField(max_length=100)),
                ('inspector_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
