# Generated by Django 5.2.7 on 2026-03-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_certificatecounter_seed_sequences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('builders_form', 'Builders Form'), ('motorized_certification', 'Motorized Certification'), ('marine_certification', 'Marine Certification'), ('exclusive_fish_privilege', 'Exclusive Fish Privilege')], default='marine_certification', help_text='Form category: Builders, Motorized, Marine, or Exclusive Fish.', max_length=32, verbose_name='Certificate type'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='license_type',
            field=models.CharField(max_length=20, verbose_name='License (New / Renew)'),
        ),
    ]
