# Generated by Django 4.2.29 on 2026-04-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_photoreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoreport',
            name='accuracy_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photoreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photoreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
